-- MySQL Script generated by MySQL Workbench
-- 06/06/19 19:35:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cms` DEFAULT CHARACTER SET utf8 ;
USE `cms` ;

-- -----------------------------------------------------
-- Table `cms`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`sessao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`conteudo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_publicacao` DATETIME NOT NULL,
  `titulo` VARCHAR(150) NOT NULL,
  `texto` TEXT NOT NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  `sessao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conteudo_sessao1_idx` (`sessao_id` ASC),
  CONSTRAINT `fk_conteudo_sessao1`
    FOREIGN KEY (`sessao_id`)
    REFERENCES `cms`.`sessao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`acervo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`acervo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `texto` VARCHAR(255) NULL,
  `arquivo` VARCHAR(150) NOT NULL,
  `mine` VARCHAR(50) NOT NULL,
  `ordem` INT NOT NULL DEFAULT 0,
  `ativo` BIT NOT NULL DEFAULT 1,
  `conteudo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acervo_conteudo_idx` (`conteudo_id` ASC),
  CONSTRAINT `fk_acervo_conteudo`
    FOREIGN KEY (`conteudo_id`)
    REFERENCES `cms`.`conteudo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `usuario` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
